// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nugnzlunhbxwndogshef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51Z256bHVuaGJ4d25kb2dzaGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTE0NTUsImV4cCI6MjA2MzgyNzQ1NX0.Oss5KL99MaQB5MpIpWS-qXAvvC2OjI1ECSa-EMhA-3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);